name: Run Unit Tests

on: [pull_request]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: bitnami/postgresql
        ports:
          - 5432:5432
        env:
          POSTGRES_USERNAME: docker
          POSTGRES_PASSWORD: docker
          POSTGRES_DATABASE: apigympass

    steps:
      - uses: actions/checkout@v3 # download code
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'

      - run: npm ci # skip all verifications, install all deps only

      - run: npm run test:e2e
        env:
          JWT_SECRET: testing
          PORT: 3333
          DATABASE_URL: 'postgresql://docker:docker@localhost:5432/apigympass?schema=public'
